@startuml
'left to right direction

package unity {

    abstract class GameObject {
        +Instaniate(prefab: Prefab): void
        +Destroy(): void
    }

    note left of GameObject {
        Instantiate() method is the constructor
        Destroy() method removes the instance entirely
    }


    class DroneManager <<GameObject>> extends GameObject {
    }


    class Panel <<GameObject>> extends GameObject {
        CubeVisualizationToggle: GameObject
        IntensitySlider: GameObject
    }

    class CubeVisualizationToggle <<GameObject>> extends GameObject {
    }

    class IntensitySlider <<GameObject>> extends GameObject {
        IntensityValue: GameObject
    }

    class IntensityValue <<GameObject>> extends GameObject {
        LightIntensityText: Script
    }
    class Directional_Light <<GameObject>> extends GameObject {
        -Light: Script
        -Text: Script
    }

    class Main_Camera <<GameObject>> extends GameObject {
        -Controller: Script
    }

    class DroneCamera <<GameObject>> extends GameObject {
        -Controller: Script
    }

    class CameraManager <<GameObject>> extends GameObject {
    }

    class Floor <<GameObject>> extends GameObject {
    }

    class EventSystem <<GameObject>> extends GameObject {
    }

    class Canvas <<GameObject>> extends GameObject {
        Panel: GameObject
    }

    class WallManager <<GameObject>> extends GameObject {
    }

    class CSVLogic <<GameObject>> extends GameObject {
        CSVLogic: Script
    }


    Canvas --> Panel
    Floor --> EventSystem
    CameraManager --> DroneCamera
    CameraManager --> Main_Camera
    Panel --> CubeVisualizationToggle
    Panel --> IntensitySlider
    IntensitySlider --> IntensityValue
    DroneManager --> CSVLogic
    AutoCameraController --> CSVLogic

}

package scripts {

    +class MissionControl {
        -_startDroneId: int
        -_exitDroneId: int
        +csvLogic: CSVLogic
        +droneManager: DroneManager
        +autoCam: AutoCameraController
        +droneCam: DroneCameraController
        -Start(): void
        -Update(): void


    }

    +class CubeManager {
        -_uprightfrontPos: Vector3
        -_upleftbackPos: Vector3
        -_botcenterPos: Vector3
        -_boxCenter: Vector3
        -_cubes: List<GameObject>
        -_currMode: string
        -_camTrackMode: string
        -_currAllPossibleMode: string
        -_currCubeCommand: string
        -_cubeToRemove: GameObject
        -Start(): void
        -Update(): void
        +UpdateCube(): void
        +UpdateCubeRender(isOn: bool): void
        +GetBoxLeftBackPos(): Vector3
        +GetBoxRightFrontPos(): Vector3
        +GetBoxCenterPos(): Vector3
        +{static}cubeCenter(bottomLeftBackConertDronePos: Vector3, spacing: float): void
        +{static} UpdateCornerPosAddCube(cubeCenter: Vector3, scaling: float, uprightfrontPos: Vector3, upleftbackPos: Vector3, botCenterPos: Vector3, boxCenter: Vector3): void
        +{static} UpdateCornerPosSubCube(cubeCenter: Vector3, scaling: float, uprightfrontPos: Vector3, upleftbackPos: Vector3, botCenterPos: Vector3, boxCenter: Vector3, axis: String): void
        +{static}DefaultSaddleCube(xPos: float, yPos: float, zPos: float): void
    }

    +class CSVLogic {
        -_cubeRenderFolderPath: String
        -_currentChangesLine: List<string>
        -_counter: int
        -_streamingFilePath: string
        -_currentStreamingFile: Dictionary<int, Tuple<Vector3, string, Vector3, Vector3, string>>
        -_currentFrame: int
        -_firstFrame: bool

        -Start(): void
        +FetchChangesCSV(): void
        +ReadChanges(): string
        +UpdateChanges(): string
        +FetchStreaming(): Dictionary<int, Tuple<Vector3, string, Vector3, Vector3, string>>
        +ParseStreaming(): Tuple<int, int>
        +ReadStreaming(): Dictionary<int, Tuple<Vector3, string, Vector3, Vector3, string>>
        +UpdateStreaming(): Tuple<int, int>
    }

    +class AutoCameraController {
        +rotationSpeed: float
        +moveSpeed: float
        +rotationSmoothTime: float
        +movementSmoothTime: float
        +camScaleDistToBoxEdgeX: float
        +camScaleDistToBoxEdgeY: float
        +camScaleDistToBoxEdgeZ: float
        +camInterpolationSpeed: float
        -_camLerpVal: float
        -_camMovementPriority: bool
        -targetRotation: Quaternion
        -targetPosition: Vector3
        -startRotation: Quaternion
        -startPosition: Vector3
        -_camPathLeftBackPos: Vector3
        -_camPathRightBackPos: Vector3
        -_camPathLeftFrontPos: Vector3
        -_camPathRightFrontPos: Vector3
        -_upRightFrontPos: Vector3
        -_upLeftBackPos: Vector3
        -_camPathCornerList: List<Vector3>
        -_oldCamPathCornerList: List<Vector3>
        -_startCornerIndex: int
        -_endCornerIndex: int
        -_currLoopStartIndex: int
        -_currBoxCenter: Vector3
        -isRotating: bool
        -_camStartRotation: Quaternion
        -_camTargetRotation: Quaternion
        -rotationTimer: float
        -_camRotationSpeed: float
        +rotationDuration: float
        -OnTargetChanged(newTargetPosition: Vector3): void
        +FollowDrone(drone: GameObject): void
        +GetCameraMovementPriority(): bool
        -Start(): void
        -Update(): void
        -UpdateCamPathPlane(): void
        +_UniformScaleCamPathCornerList(scale: float): List<Vector3>
        -AutoCamMovement(cornerList: List<Vector3>): void
        -InterpolateCamPos(startPos: Vector3, endPos: Vector3, inModeMovement: bool): bool
        -Reset(): void
    }

    +class ArrowDrawer <<MonoBehaviour>> {
        -arrowBody: GameObject
        -arrowHead: GameObject
        +arrowHeadSize: float
        +arrowBodyWidth: float
        +Update(): void
        +CreateArrow(droneId: int, startPos: Vector3, endPos: Vector3, color: string): void
        +UpdateArrow(startPos: Vector3, endPos: Vector3, color: string): void
        +DestroyArrow(): void
        -CreateCone(radius: float, height: float): GameObject
        +UpdateArrowHead(startPos: Vector3, endPos: Vector3, color: string): void
        +UpdateArrowBody(startPos: Vector3, endPos: Vector3, color: string): void
    }

    +class CameraManager <<MonoBehaviour>> {
        -_cameraManager: ICameraManager
        +autoCameraController: AutoCameraController
        +droneCameraController: DroneCameraController
        +autoCameraActive: bool
        +Start(): void
        +GetCameraMovementPriority(): bool
        +GetAutoCameraActive(): bool
        +FollowDrone(drone: GameObject): void
    }

    +class ChargingBlockManager <<MonoBehaviour>> {

        -_centerToTop: float
        -_widthX: float
        -_widthZ: float
        -_droneThickness: float
        -Start(): void
        -MakeChargingBlock(): void
        +setLocation(startPos: Vector3, endPos: Vector3, chargeDronePos: Vector3): void
    }

    +interface ICameraManager {
        +GetCameraMovementPriority(): bool
        +FollowDrone(drone: GameObject): void
    }

    +class DroneCameraController <<MonoBehaviour>> implements ICameraManager {
        +droneManager: DroneManager
        +camYOffset: float
        -_camMovementPriority: bool
        -_lerpVal: float
        -rotationTimer: float
        -rotationDuration: float
        -_startRotation: Quaternion
        -_startPos: Vector3
        -_endPos: Vector3
        -_chargedDroneStartPos: Vector3
        -_trackDroneId: int
        -_trackedDronePos: Vector3
        -_currDroneInfo: Tuple<int, Vector3, Vector3, Vector3>
        -_currForward: Vector3
        -_targetForward: Vector3
        -_currentDrone: Transform
        -_currentDroneObject: Tuple<int, GameObject>
        -_currentFollowedDroneId: int
        -_isSwitching: bool

        +GetCameraMovementPriority(): bool

        +Start(): void
        +Update(): void
        -SwitchFollowDelayed(droneId: int): IEnumerator
        +FollowDrone(drone: GameObject): void
        +_assignFields(): void
        +_InterpolateToEndPosition(): bool
        +_CamPlacementOnTrackedDrone(): void
        +_FinishRotateCam(): void
    }

    +class DroneManager {
        +dronePrefab: GameObject
        +droneArrowPrefab: GameObject
        +chargingBlockPrefab: GameObject
        +defaultCubePrefab: GameObject
        +invertCubePrefab: GameObject
        +cubeToggle: Toggle
        +spacing: float
        +interpolationSpeed: float
        +switchDroneFollow: bool

        -_drones: Dictionary<int, GameObject>
        -_droneInfo: Dictionary<int, Tuple<Vector3, string, Vector3, Vector3, string>>
        -_droneArrows: Dictionary<int, GameObject>
        -_droneRotations: Dictionary<int, Tuple<Quaternion, Quaternion>>
        -_cubeToggleState: bool
        -_isSimulating: bool
        -_userPause: bool
        -_continueMode: bool
        -_lerpVal: float
        -_chargedDroneStartPos: Vector3
        -_trackDroneId: int
        -_drainedDroneId: int
        -_droneCamPos: Vector3
        -_droneCamFaceDirection: Vector3
        -rotationTimer: float
        -rotationDuration: float
        -_t: float
        -_droneRotatePriority: bool
        -switchDroneFollow: bool
        -{const}RotationDurationDroneCam: float

        -Start(): void
        -Update(): void
        +InitializeDrones(setSpacing: float): void
        -UpdateDrones(): void
        -InterpolateToEndPosition(): bool
        -GenerateChargingDrones(): void
        -ResetChargingDrones(): void
        -GenerateChargingDrones(): void
        -_MakeNewDrone(droneId: int, color: string, position: Vector3): void
        -_StoreDroneRotation(droneId: int): void
        -_FinishRotateDrone(droneId: int): void
    }


    +class LightIntensity <<MonoBehaviour>> {
        +slider: Slider
        -_light: Light
        -Awake(): void
        -Start(): void
        -UpdateLight(val: float): void
    }

    +class LightIntensityText <<MonoBehaviour>> {
        +slider: Slider
        +_text: Text
        -Awake(): void
        -Start(): void
        -UpdateText(val: float): void
    }

    +static class Utils {
        +{static} CreateColorFromCsvName(color: string): UnityEngine.Color
        +{static}FindClosestPoint(currentPosition: Vector3, positions: List<Vector3>): int
        +{static}rotateYX(v: Vector3): Vector3
    }

    +class WallManager <<MonoBehaviour>> {
        +brickPrefab: GameObject
        +bricksPerSide: int
        +brickLength: float
        +brickThickness: float
        +offsetFromCenter: float
        +bricksHigh: int
        -_floorHeight: float

        -Start(): void
        -BuildWall(center: Vector3, direction: Vector3, length: float, facing: Vector3): void
    }

    "unity.WallManager" --> WallManager
    "unity.DroneManager" --> "scripts.DroneManager"
    "unity.CameraManager" --> "scripts.CameraManager"
    Main_Camera --> AutoCameraController
    DroneCamera --> DroneCameraController
    Directional_Light --> LightIntensity
    LightIntensityText --> IntensitySlider
    LightIntensity --> IntensitySlider
    CameraManager --> ICameraManager
    CameraManager --> AutoCameraController
    CameraManager --> DroneCameraController
    AutoCameraController --> DroneManager
    DroneManager ..> Utils
    DroneCameraController --> DroneManager
    ArrowDrawer ..> Utils
    IntensityValue --> LightIntensityText
    "unity.DroneManager" --> "scripts.CSVLogic"
    "unity.Main_Camera" --> "scripts.CSVLogic"
    MissionControl --> DroneManager
    MissionControl --> AutoCameraController
    MissionControl --> DroneCameraController
    MissionControl --> ChargingBlockManager
    MissionControl --> CSVLogic
    MissionControl --> ArrowDrawer
    MissionControl --> CubeManager
    "unity.CSVLogic" --> "scripts.CSVLogic"

}

package datasource {

    abstract class Prefab extends "unity.GameObject" {

    }
    note right of Prefab {
        script field is the name of the script
        associated with the prefab
        (e.g. ChargingBlockPrefab uses
        "ChargingBlockManager" in script package)
    }

    class DronePrefab <<Prefab>> extends Prefab {

    }

    class ChargingBlockPrefab <<Prefab>> extends Prefab {
        -ChargingBlock: Script
    }

    class ArrowDrawerPrefab <<Prefab>> extends Prefab {
        -ArrowDrawer: Script
    }

    class DefaultSaddleCubePrefab <<Prefab>> extends Prefab {

    }

    class InvertSaddleCubePrefab <<Prefab>> extends Prefab {

    }
    class WallPrefab <<Prefab>> extends Prefab {

    }

    package CSVFiles {

        class File1 <<CSVfile>> {
            +columns: [timestamp, droneId, x, y, z]
            +rows: drone
        }

        note left of File1 {
            There are 587 such files that contain
            drone data for each step in the simulation
        }

    }

    class changes <<CSVfile>> {
        +columns: [mode, x, y, z, subtract direction]
        +rows: next cube generation step
    }

    note left of changes {
        This is the master CSV file that
        creates the other 587 files
    }



    "scripts.CSVLogic" ..> changes
    "scripts.CSVLogic" ..> File1

}

"unity.WallManager" --> WallPrefab
"unity.DroneManager" --> ChargingBlockPrefab
ChargingBlockPrefab --> ChargingBlockManager
"unity.DroneManager" --> ArrowDrawerPrefab
ArrowDrawerPrefab --> ArrowDrawer
"unity.DroneManager" --> DronePrefab
"scripts.CubeManager" --> DefaultSaddleCubePrefab
"scripts.CubeManager" --> InvertSaddleCubePrefab
"scripts.DroneManager" --> DronePrefab
"scripts.DroneManager" --> ChargingBlockPrefab
WallPrefab --> "scripts.WallManager"

@enduml